name: Update Markdown TOCs

on:
  push:
    branches: [master]
    paths: ["README.md", "DEVELOPMENT.md"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 5
    env:
      GITHUB_MARKDOWN_TOC_VERSION: 0.10.0 # See https://github.com/ekalinin/github-markdown-toc/releases
    steps:
      - uses: actions/checkout@v4
      - run: |
          curl https://raw.githubusercontent.com/ekalinin/github-markdown-toc/${GITHUB_MARKDOWN_TOC_VERSION}/gh-md-toc -o gh-md-toc
          chmod a+x gh-md-toc
          ./gh-md-toc --insert --no-backup --hide-footer README.md DEVELOPMENT.md
      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: Auto update markdown TOC
